// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKDSTicket = `-- name: CreateKDSTicket :one
INSERT INTO kds_tickets (
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority
)
VALUES (
    $1,
    $2,
    $3,
    'pending',
    $4
)
RETURNING
    id,
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority,
    started_at,
    ready_at,
    completed_at,
    created_at,
    updated_at
`

type CreateKDSTicketParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	OrderID      pgtype.UUID `json:"order_id"`
	Priority     int32       `json:"priority"`
}

func (q *Queries) CreateKDSTicket(ctx context.Context, arg CreateKDSTicketParams) (KdsTicket, error) {
	row := q.db.QueryRow(ctx, createKDSTicket,
		arg.TenantID,
		arg.RestaurantID,
		arg.OrderID,
		arg.Priority,
	)
	var i KdsTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RestaurantID,
		&i.OrderID,
		&i.Status,
		&i.Priority,
		&i.StartedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKDSTicketByID = `-- name: GetKDSTicketByID :one
SELECT
    id,
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority,
    started_at,
    ready_at,
    completed_at,
    created_at,
    updated_at
FROM kds_tickets
WHERE tenant_id = $1
  AND id = $2
`

type GetKDSTicketByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetKDSTicketByID(ctx context.Context, arg GetKDSTicketByIDParams) (KdsTicket, error) {
	row := q.db.QueryRow(ctx, getKDSTicketByID, arg.TenantID, arg.ID)
	var i KdsTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RestaurantID,
		&i.OrderID,
		&i.Status,
		&i.Priority,
		&i.StartedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKDSTicketByOrderID = `-- name: GetKDSTicketByOrderID :one
SELECT
    id,
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority,
    started_at,
    ready_at,
    completed_at,
    created_at,
    updated_at
FROM kds_tickets
WHERE tenant_id = $1
  AND order_id = $2
`

type GetKDSTicketByOrderIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrderID  pgtype.UUID `json:"order_id"`
}

func (q *Queries) GetKDSTicketByOrderID(ctx context.Context, arg GetKDSTicketByOrderIDParams) (KdsTicket, error) {
	row := q.db.QueryRow(ctx, getKDSTicketByOrderID, arg.TenantID, arg.OrderID)
	var i KdsTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RestaurantID,
		&i.OrderID,
		&i.Status,
		&i.Priority,
		&i.StartedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKDSQueue = `-- name: ListKDSQueue :many
SELECT
    id,
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority,
    started_at,
    ready_at,
    completed_at,
    created_at,
    updated_at
FROM kds_tickets
WHERE tenant_id = $1
  AND restaurant_id = $2
  AND status IN (
      'pending',
      'preparing',
      'ready'
  )
ORDER BY
    priority DESC,
    created_at ASC
`

type ListKDSQueueParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) ListKDSQueue(ctx context.Context, arg ListKDSQueueParams) ([]KdsTicket, error) {
	rows, err := q.db.Query(ctx, listKDSQueue, arg.TenantID, arg.RestaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KdsTicket
	for rows.Next() {
		var i KdsTicket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RestaurantID,
			&i.OrderID,
			&i.Status,
			&i.Priority,
			&i.StartedAt,
			&i.ReadyAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKDSStatus = `-- name: UpdateKDSStatus :one
UPDATE kds_tickets
SET
    status = $3,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING
    id,
    tenant_id,
    restaurant_id,
    order_id,
    status,
    priority,
    started_at,
    ready_at,
    completed_at,
    created_at,
    updated_at
`

type UpdateKDSStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Status   KdsStatus   `json:"status"`
}

func (q *Queries) UpdateKDSStatus(ctx context.Context, arg UpdateKDSStatusParams) (KdsTicket, error) {
	row := q.db.QueryRow(ctx, updateKDSStatus, arg.TenantID, arg.ID, arg.Status)
	var i KdsTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RestaurantID,
		&i.OrderID,
		&i.Status,
		&i.Priority,
		&i.StartedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
