// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RestaurantID pgtype.UUID        `json:"restaurant_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Status       string             `json:"status"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
