// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    tenant_id,
    order_id,
    menu_item_id,
    item_name,
    unit_price,
    quantity,
    subtotal,
    notes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    tenant_id,
    order_id,
    menu_item_id,
    item_name,
    unit_price,
    quantity,
    subtotal,
    notes,
    created_at
`

type CreateOrderItemParams struct {
	TenantID   pgtype.UUID    `json:"tenant_id"`
	OrderID    pgtype.UUID    `json:"order_id"`
	MenuItemID pgtype.UUID    `json:"menu_item_id"`
	ItemName   string         `json:"item_name"`
	UnitPrice  pgtype.Numeric `json:"unit_price"`
	Quantity   int32          `json:"quantity"`
	Subtotal   pgtype.Numeric `json:"subtotal"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.TenantID,
		arg.OrderID,
		arg.MenuItemID,
		arg.ItemName,
		arg.UnitPrice,
		arg.Quantity,
		arg.Subtotal,
		arg.Notes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.MenuItemID,
		&i.ItemName,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT
    id,
    tenant_id,
    order_id,
    menu_item_id,
    item_name,
    unit_price,
    quantity,
    subtotal,
    notes,
    created_at
FROM order_items
WHERE tenant_id = $1
  AND id = $2
`

type GetOrderItemByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetOrderItemByID(ctx context.Context, arg GetOrderItemByIDParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, arg.TenantID, arg.ID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderID,
		&i.MenuItemID,
		&i.ItemName,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
    id,
    tenant_id,
    order_id,
    menu_item_id,
    item_name,
    unit_price,
    quantity,
    subtotal,
    notes,
    created_at
FROM order_items
WHERE tenant_id = $1
  AND order_id = $2
ORDER BY created_at ASC
`

type ListOrderItemsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrderID  pgtype.UUID `json:"order_id"`
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.TenantID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.MenuItemID,
			&i.ItemName,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
