// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    tenant_id,
    restaurant_id,
    customer_id,
    status,
    total_amount,
    currency,
    created_at,
    updated_at
FROM orders
WHERE tenant_id = $1
  AND id = $2
`

type GetOrderByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetOrderByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RestaurantID pgtype.UUID        `json:"restaurant_id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	Status       OrderStatus        `json:"status"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.TenantID, arg.ID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RestaurantID,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
