// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
