// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restaurants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateRestaurant = `-- name: ActivateRestaurant :one
UPDATE restaurants
SET
    status = 'active',
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
`

type ActivateRestaurantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ActivateRestaurant(ctx context.Context, arg ActivateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, activateRestaurant, arg.TenantID, arg.ID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
`

type CreateRestaurantParams struct {
	ID           pgtype.UUID      `json:"id"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
	Name         string           `json:"name"`
	Slug         string           `json:"slug"`
	Description  pgtype.Text      `json:"description"`
	Phone        pgtype.Text      `json:"phone"`
	Email        pgtype.Text      `json:"email"`
	AddressLine1 pgtype.Text      `json:"address_line_1"`
	AddressLine2 pgtype.Text      `json:"address_line_2"`
	City         pgtype.Text      `json:"city"`
	State        pgtype.Text      `json:"state"`
	PostalCode   pgtype.Text      `json:"postal_code"`
	Country      string           `json:"country"`
	Latitude     pgtype.Numeric   `json:"latitude"`
	Longitude    pgtype.Numeric   `json:"longitude"`
	Status       RestaurantStatus `json:"status"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurant,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Status,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRestaurant = `-- name: DeactivateRestaurant :one
UPDATE restaurants
SET
    status = 'inactive',
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
`

type DeactivateRestaurantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeactivateRestaurant(ctx context.Context, arg DeactivateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, deactivateRestaurant, arg.TenantID, arg.ID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
FROM restaurants
WHERE tenant_id = $1
  AND id = $2
`

type GetRestaurantByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetRestaurantByID(ctx context.Context, arg GetRestaurantByIDParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByID, arg.TenantID, arg.ID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantBySlug = `-- name: GetRestaurantBySlug :one
SELECT
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
FROM restaurants
WHERE tenant_id = $1
  AND slug = $2
`

type GetRestaurantBySlugParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Slug     string      `json:"slug"`
}

func (q *Queries) GetRestaurantBySlug(ctx context.Context, arg GetRestaurantBySlugParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantBySlug, arg.TenantID, arg.Slug)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
FROM restaurants
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListRestaurantsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error) {
	rows, err := q.db.Query(ctx, listRestaurants, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Restaurant
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Phone,
			&i.Email,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendRestaurant = `-- name: SuspendRestaurant :one
UPDATE restaurants
SET
    status = 'suspended',
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
`

type SuspendRestaurantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SuspendRestaurant(ctx context.Context, arg SuspendRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, suspendRestaurant, arg.TenantID, arg.ID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRestaurant = `-- name: UpdateRestaurant :one
UPDATE restaurants
SET
    name = $3,
    slug = $4,
    description = $5,
    phone = $6,
    email = $7,
    address_line_1 = $8,
    address_line_2 = $9,
    city = $10,
    state = $11,
    postal_code = $12,
    country = $13,
    latitude = $14,
    longitude = $15,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING
    id,
    tenant_id,
    name,
    slug,
    description,
    phone,
    email,
    address_line_1,
    address_line_2,
    city,
    state,
    postal_code,
    country,
    latitude,
    longitude,
    status,
    created_at,
    updated_at
`

type UpdateRestaurantParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  pgtype.Text    `json:"description"`
	Phone        pgtype.Text    `json:"phone"`
	Email        pgtype.Text    `json:"email"`
	AddressLine1 pgtype.Text    `json:"address_line_1"`
	AddressLine2 pgtype.Text    `json:"address_line_2"`
	City         pgtype.Text    `json:"city"`
	State        pgtype.Text    `json:"state"`
	PostalCode   pgtype.Text    `json:"postal_code"`
	Country      string         `json:"country"`
	Latitude     pgtype.Numeric `json:"latitude"`
	Longitude    pgtype.Numeric `json:"longitude"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, updateRestaurant,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Phone,
		arg.Email,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
